#!/usr/bin/env bash
# Generates sdk-word-bundle.js by concatenating all required JS files
# from sdkjs in the correct dependency order for DoctRenderer (x2t PDF).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SDKJS_DIR="$PROJECT_ROOT/src/sdkjs"
BINARIES_DIR="$PROJECT_ROOT/src-tauri/binaries"
OUTPUT="$BINARIES_DIR/sdk-word-bundle.js"
CONFIG="$SDKJS_DIR/configs/word.json"

if [ ! -f "$CONFIG" ]; then
    echo "ERROR: $CONFIG not found"
    exit 1
fi

NATIVE_FILES=(
    "$SDKJS_DIR/vendor/polyfill.js"
    "$SDKJS_DIR/common/Native/native.js"
    "$SDKJS_DIR/common/Native/jquery_native.js"
    "$BINARIES_DIR/native_shim.js"
)

extract_paths() {
    local json_file="$1"
    local jq_filter="$2"
    python3 -c "
import json, sys
with open('$json_file') as f:
    data = json.load(f)
keys = '$jq_filter'.split('.')
obj = data
for k in keys:
    obj = obj[k]
for p in obj:
    print(p)
"
}

echo "Generating sdk-word-bundle.js..."

> "$OUTPUT"

echo "// sdk-word-bundle.js - Generated by scripts/generate-sdk-bundle.sh" >> "$OUTPUT"
echo "// Do not edit manually." >> "$OUTPUT"

count=0
for f in "${NATIVE_FILES[@]}"; do
    if [ -f "$f" ]; then
        cat "$f" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        count=$((count + 1))
    else
        echo "WARNING: Native file not found: $f"
    fi
done

for section in "sdk.min" "sdk.desktop.min" "sdk.common" "sdk.desktop.common"; do
    paths=$(extract_paths "$CONFIG" "$section")
    while IFS= read -r relpath; do
        relpath=$(echo "$relpath" | tr -d '[:space:]')
        [ -z "$relpath" ] && continue
        fullpath="$SDKJS_DIR/$relpath"
        if [ -f "$fullpath" ]; then
            cat "$fullpath" >> "$OUTPUT"
            echo "" >> "$OUTPUT"
            count=$((count + 1))
        else
            echo "WARNING: $relpath not found"
        fi
    done <<< "$paths"
done

size=$(wc -c < "$OUTPUT")
echo "sdk-word-bundle.js: $count files, $(( size / 1024 / 1024 ))MB"
