# Euro-Office Lite - Font preparation script
# Downloads Liberation Sans, XOR-encodes for sdkjs, and generates AllFonts.js
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts\prepare-fonts.ps1

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$fontsDir = Join-Path $projectRoot "src\fonts"
$allFontsPath = Join-Path $projectRoot "src\sdkjs\common\AllFonts.js"
$tempDir = Join-Path $env:TEMP "euro-office-fonts"

# Fonts are stored as plain TTF (no XOR encoding needed).
# Local/common.js overrides LoadFontAsync and does NOT apply XOR decode.

$liberationVersion = "2.1.5"
$liberationUrl = "https://github.com/liberationfonts/liberation-fonts/files/7261482/liberation-fonts-ttf-2.1.5.tar.gz"

# Font definitions
$fontDefs = @(
    @{ File = "LiberationSans-Regular.ttf";    Family = "Liberation Sans"; Style = "R" },
    @{ File = "LiberationSans-Italic.ttf";     Family = "Liberation Sans"; Style = "I" },
    @{ File = "LiberationSans-Bold.ttf";       Family = "Liberation Sans"; Style = "B" },
    @{ File = "LiberationSans-BoldItalic.ttf"; Family = "Liberation Sans"; Style = "BI" }
)

Write-Host ""
Write-Host "=== Euro-Office Lite - Font Preparation ===" -ForegroundColor Cyan

# 1. Download Liberation Sans
if (-not (Test-Path $tempDir)) { New-Item -ItemType Directory -Path $tempDir | Out-Null }
$tarGzPath = Join-Path $tempDir "liberation-fonts.tar.gz"

if (-not (Test-Path $tarGzPath)) {
    Write-Host "[1/4] Downloading Liberation Sans..." -ForegroundColor Yellow
    Invoke-WebRequest -Uri $liberationUrl -OutFile $tarGzPath -UseBasicParsing
} else {
    Write-Host "[1/4] Using cached download..." -ForegroundColor DarkGray
}

# 2. Extract
Write-Host "[2/4] Extracting fonts..." -ForegroundColor Yellow
$extractDir = Join-Path $tempDir "extracted"
if (Test-Path $extractDir) { Remove-Item -Recurse -Force $extractDir }
New-Item -ItemType Directory -Path $extractDir | Out-Null
tar -xzf $tarGzPath -C $extractDir

# Find the TTF directory
$ttfDir = Get-ChildItem -Path $extractDir -Recurse -Directory | Where-Object { $_.Name -match "liberation-fonts-ttf" } | Select-Object -First 1
if (-not $ttfDir) {
    throw "Could not find extracted font directory"
}

# 3. Copy plain TTF files to src/fonts/
Write-Host "[3/4] Copying fonts..." -ForegroundColor Yellow
if (-not (Test-Path $fontsDir)) { New-Item -ItemType Directory -Path $fontsDir | Out-Null }

foreach ($def in $fontDefs) {
    $srcFile = Join-Path $ttfDir.FullName $def.File
    if (-not (Test-Path $srcFile)) {
        throw ("Font file not found: " + $srcFile)
    }
    $destFile = Join-Path $fontsDir $def.File
    Copy-Item -Path $srcFile -Destination $destFile -Force
    Write-Host ("  Copied: " + $def.File) -ForegroundColor DarkGreen
}

# 4. Generate AllFonts.js
Write-Host "[4/4] Generating AllFonts.js..." -ForegroundColor Yellow

# Build __fonts_files array
$filesList = @()
foreach ($def in $fontDefs) {
    $filesList += ('"' + $def.File + '"')
}
$filesArray = $filesList -join ", "

# Build __fonts_infos array
# Format: [name, indexR, faceR, indexI, faceI, indexB, faceB, indexBI, faceBI]
$indexR = -1; $indexI = -1; $indexB = -1; $indexBI = -1
for ($i = 0; $i -lt $fontDefs.Count; $i++) {
    switch ($fontDefs[$i].Style) {
        "R"  { $indexR  = $i }
        "I"  { $indexI  = $i }
        "B"  { $indexB  = $i }
        "BI" { $indexBI = $i }
    }
}
$infosEntry = '["Liberation Sans", ' + $indexR + ', 0, ' + $indexI + ', 0, ' + $indexB + ', 0, ' + $indexBI + ', 0]'
$arialAlias = '["Arial", ' + $indexR + ', 0, ' + $indexI + ', 0, ' + $indexB + ', 0, ' + $indexBI + ', 0]'
$calibriAlias = '["Calibri", ' + $indexR + ', 0, ' + $indexI + ', 0, ' + $indexB + ', 0, ' + $indexBI + ', 0]'
$helveticaAlias = '["Helvetica", ' + $indexR + ', 0, ' + $indexI + ', 0, ' + $indexB + ', 0, ' + $indexBI + ', 0]'

$nl = [char]10
$content = '// Generated by scripts/prepare-fonts.ps1 -- do not edit manually.' + $nl
$content += 'window["__fonts_files"] = [' + $filesArray + '];' + $nl
$content += 'window["__fonts_infos"] = [' + $nl
$content += '    ' + $infosEntry + ',' + $nl
$content += '    ' + $arialAlias + ',' + $nl
$content += '    ' + $calibriAlias + ',' + $nl
$content += '    ' + $helveticaAlias + $nl
$content += '];' + $nl
$content += 'window["g_fonts_selection_bin"] = "";' + $nl

[System.IO.File]::WriteAllText($allFontsPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host ""
Write-Host "=== Font preparation complete ===" -ForegroundColor Green
Write-Host ("Fonts encoded in: " + $fontsDir)
Write-Host ("AllFonts.js updated: " + $allFontsPath)
Write-Host ""
