# Euro-Office Lite — Setup script
# Run once after cloning, or after `git submodule update`
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts\setup.ps1

param(
    [switch]$SkipNpmInstall
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)

Write-Host "`n=== Euro-Office Lite Setup ===" -ForegroundColor Cyan

# 1. Initialize submodules
Write-Host "`n[1/4] Initializing git submodules..." -ForegroundColor Yellow
Push-Location $projectRoot
git submodule update --init --recursive
Pop-Location

# 2. Install sdkjs build dependencies
$sdkjsBuild = Join-Path $projectRoot "src\sdkjs\build"
if (-not $SkipNpmInstall) {
    Write-Host "`n[2/4] Installing sdkjs build dependencies..." -ForegroundColor Yellow
    Push-Location $sdkjsBuild
    npm ci
    Pop-Location
} else {
    Write-Host "`n[2/4] Skipping npm install (-SkipNpmInstall)" -ForegroundColor DarkGray
}

# 3. Generate develop scripts (scripts.js for word/cell/slide)
Write-Host "`n[3/4] Building sdkjs develop scripts (--desktop=true)..." -ForegroundColor Yellow
Push-Location $sdkjsBuild
npx grunt develop --desktop=true
Pop-Location

# Patch word/scripts.js to include editor.js (provides AscCommon.getEmpty)
$wordScripts = Join-Path $projectRoot "src\sdkjs\develop\sdkjs\word\scripts.js"
$content = Get-Content $wordScripts -Raw -Encoding utf8
if ($content -notmatch 'word/document/editor\.js') {
    Write-Host "  Patching word/scripts.js with editor.js..." -ForegroundColor DarkYellow
    $content = $content -replace '\];$', ",`n`t`"../../../../sdkjs/word/document/editor.js`"`n];"
    Set-Content $wordScripts -Value $content -Encoding utf8 -NoNewline
}

# 4. Create AllFonts.js stub (font index populated at runtime)
Write-Host "`n[4/4] Creating AllFonts.js stub..." -ForegroundColor Yellow
$allFontsPath = Join-Path $projectRoot "src\sdkjs\common\AllFonts.js"
$allFontsContent = @'
// Generated by scripts/setup.ps1 — do not edit manually.
// Stub: font index will be populated by system font scanner at runtime.
window["__fonts_files"] = [];
window["__fonts_infos"] = [];
window["g_fonts_selection_bin"] = "";
'@
Set-Content $allFontsPath -Value $allFontsContent -Encoding utf8

Write-Host "`n=== Setup complete ===" -ForegroundColor Green
Write-Host "Run 'npx tauri dev' to start the app.`n"
